/**
 * scripts/seedRoles.js — Sequelize version
 *
 * Seeds the default admin roles into the cedi_auth.roles table.
 * Safe to run multiple times (upsert by name).
 */
require('dotenv').config();
const connectDB = require('../config/database');
const { Role } = require('../models');

const defaultRoles = [
  {
    name: 'super-admin',
    displayName: 'Super Administrator',
    description: 'Full system access with all permissions',
    hierarchy: 1,
    isActive: true,
    permissions: {
      menus: {
        user: true,
        userManagement: true,
        order: true,
        fundManagement: true,
        creditReview: true,
        preCollection: true,
        collection: true,
        appConfiguration: true,
        dataStatistics: true,
        system: true,
        contentManagement: true,
        notificationManagement: true,
        marketing: true,
      },
      subMenus: {
        user: {
          listOfUsers: true,
          findOne: true,
          manualRegistration: true,
          userManagement: true,
          levelAssignment: true,
        },
        order: {
          orderList: true,
          orderLending: true,
          orderRepayment: true,
          reviewRepayment: true,
          extensionOrder: true,
          loanDetails: true,
        },
        creditReview: { assign: true, list: true, count: true },
        preCollection: {
          list: true,
          allList: true,
          paymentRecord: true,
          rank1: true,
          rank2: true,
        },
        collection: {
          list: true,
          rank1: true,
          rank2: true,
          paymentRecord: true,
          officers: true,
        },
        appConfiguration: {
          generalSettings: true,
          loanSettings: true,
          loanConfiguration: true,
          loanRateCalculation: true,
          appBranding: true,
          contactInfo: true,
          faq: true,
          termsConditions: true,
        },
        fundManagement: { paymentManagement: true },
        dataStatistics: { dashboard: true },
        system: { adminManagement: true, roleManagement: true },
      },
      dataAccess: {
        viewAllLoans: true,
        viewAssignedLoans: true,
        viewAllUsers: true,
        viewPayments: true,
        editUserData: true,
        exportData: true,
      },
      actions: {
        createAdmin: true,
        editAdmin: true,
        deleteAdmin: true,
        manageRoles: true,
        createUser: true,
        editUsers: true,
        viewUsers: true,
        resetPin: true,
        toggleUserStatus: true,
        updateUserLevel: true,
        assignLoan: true,
        updateLoanStatus: true,
        approveLoans: true,
        rejectLoans: true,
        hangUpLoans: true,
        viewLoans: true,
        loan_clearance: true,
        updateConfiguration: true,
        updateConfig: true,
        createContent: true,
        updateContent: true,
        deleteContent: true,
        manageNotifications: true,
        managePayments: true,
      },
    },
  },
  {
    name: 'admin',
    displayName: 'Administrator',
    description: 'All operational menus except super-admin only controls',
    hierarchy: 2,
    isActive: true,
    permissions: {
      menus: {
        user: true,
        userManagement: true,
        order: true,
        fundManagement: true,
        creditReview: true,
        preCollection: true,
        collection: true,
        appConfiguration: true,
        dataStatistics: true,
        contentManagement: true,
        notificationManagement: true,
        marketing: true,
        system: true,
      },
      subMenus: {
        user: {
          listOfUsers: true,
          findOne: true,
          manualRegistration: true,
          userManagement: true,
          levelAssignment: true,
        },
        order: {
          orderList: true,
          orderLending: true,
          orderRepayment: true,
          reviewRepayment: true,
          extensionOrder: true,
          loanDetails: true,
        },
        creditReview: { assign: true, list: true, count: true },
        preCollection: {
          list: true,
          allList: true,
          paymentRecord: true,
          rank1: true,
          rank2: true,
        },
        collection: {
          list: true,
          rank1: true,
          rank2: true,
          paymentRecord: true,
          officers: true,
        },
        appConfiguration: {
          generalSettings: true,
          loanSettings: true,
          loanConfiguration: true,
          loanRateCalculation: true,
          appBranding: true,
          contactInfo: true,
          faq: true,
          termsConditions: true,
        },
        fundManagement: { paymentManagement: true },
        dataStatistics: { dashboard: true },
        system: { adminManagement: true, roleManagement: true },
      },
      dataAccess: {
        viewAllLoans: true,
        viewAssignedLoans: true,
        viewAllUsers: true,
        viewPayments: true,
        editUserData: true,
        exportData: true,
      },
      actions: {
        createAdmin: true,
        editAdmin: true,
        deleteAdmin: false,
        manageRoles: false,
        createUser: true,
        editUsers: true,
        viewUsers: true,
        resetPin: true,
        toggleUserStatus: true,
        updateUserLevel: true,
        assignLoan: true,
        updateLoanStatus: true,
        approveLoans: true,
        rejectLoans: true,
        hangUpLoans: true,
        viewLoans: true,
        loan_clearance: true,
        updateConfiguration: true,
        updateConfig: true,
        createContent: true,
        updateContent: true,
        deleteContent: true,
        manageNotifications: true,
        managePayments: true,
      },
    },
  },
  {
    name: 'local-manager',
    displayName: 'Local Manager',
    description: 'Regional operations with broad non-system access',
    hierarchy: 3,
    isActive: true,
    permissions: {
      menus: {
        user: true,
        userManagement: true,
        order: true,
        creditReview: true,
        preCollection: true,
        collection: true,
        dataStatistics: true,
      },
      subMenus: {
        user: {
          listOfUsers: true,
          findOne: true,
          manualRegistration: true,
          userManagement: true,
          levelAssignment: false,
        },
        order: {
          orderLending: true,
          orderRepayment: true,
          reviewRepayment: true,
          extensionOrder: true,
          orderList: true,
          loanDetails: true,
        },
        creditReview: { assign: true, list: true, count: true },
        preCollection: {
          list: true,
          allList: true,
          paymentRecord: true,
          rank1: true,
          rank2: true,
        },
        collection: {
          list: true,
          rank1: true,
          rank2: true,
          paymentRecord: true,
          officers: true,
        },
        dataStatistics: { dashboard: true },
      },
      dataAccess: {
        viewAllLoans: true,
        viewAssignedLoans: true,
        viewAllUsers: true,
        viewPayments: true,
        exportData: true,
      },
      actions: {
        createUser: true,
        editUsers: true,
        viewUsers: true,
        assignLoan: true,
        updateLoanStatus: true,
        approveLoans: true,
        rejectLoans: true,
        hangUpLoans: true,
        viewLoans: true,
        loan_clearance: true,
      },
    },
  },
  {
    name: 'review-lead',
    displayName: 'Review Lead',
    description: 'Supervises review officers and can decide on review outcomes',
    hierarchy: 4,
    isActive: true,
    permissions: {
      menus: { user: true, order: true, creditReview: true },
      subMenus: {
        user: { findOne: true },
        order: {
          orderLending: true,
          orderRepayment: true,
          reviewRepayment: true,
          extensionOrder: true,
        },
        creditReview: { assign: true, list: true, count: true },
      },
      dataAccess: { viewAllLoans: true, viewAssignedLoans: true },
      actions: {
        assignLoan: true,
        updateLoanStatus: true,
        approveLoans: true,
        rejectLoans: true,
        hangUpLoans: true,
        viewLoans: true,
        loan_clearance: true,
      },
    },
  },
  {
    name: 'review-officer',
    displayName: 'Review Officer',
    description: 'Reviews assigned loans and makes decisions in credit review',
    hierarchy: 5,
    isActive: true,
    permissions: {
      menus: { user: true, order: true, creditReview: true },
      subMenus: {
        user: { findOne: true },
        order: {
          orderRepayment: true,
          reviewRepayment: true,
          extensionOrder: true,
        },
        creditReview: { list: true },
      },
      dataAccess: { viewAssignedLoans: true },
      actions: {
        updateLoanStatus: true,
        approveLoans: true,
        rejectLoans: true,
        hangUpLoans: true,
        viewLoans: true,
        loan_clearance: true,
      },
    },
  },
  {
    name: 'collection-lead',
    displayName: 'Collection Lead',
    description: 'Manages collection officer assignments and performance',
    hierarchy: 6,
    isActive: true,
    permissions: {
      menus: { user: true, collection: true },
      subMenus: {
        user: { findOne: true },
        collection: {
          list: true,
          rank1: true,
          rank2: true,
          officers: true,
        },
      },
      dataAccess: { viewAllLoans: true, viewAssignedLoans: true },
      actions: { assignLoan: true, viewLoans: true },
    },
  },
  {
    name: 'collection-officer',
    displayName: 'Collection Officer',
    description: 'Works assigned overdue collection cases',
    hierarchy: 7,
    isActive: true,
    permissions: {
      menus: { user: true, collection: true },
      subMenus: { user: { findOne: true }, collection: { list: true } },
      dataAccess: { viewAssignedLoans: true },
      actions: { viewLoans: true },
    },
  },
  {
    name: 'precollection-lead',
    displayName: 'Pre-Collection Lead',
    description: 'Manages pre-collection assignments and monitoring',
    hierarchy: 8,
    isActive: true,
    permissions: {
      menus: { user: true, preCollection: true },
      subMenus: {
        user: { findOne: true },
        preCollection: {
          list: true,
          paymentRecord: true,
          rank1: true,
          allList: true,
        },
      },
      dataAccess: { viewAllLoans: true, viewAssignedLoans: true },
      actions: { viewLoans: true },
    },
  },
  {
    name: 'precollection-officer',
    displayName: 'Pre-Collection Officer',
    description: 'Works assigned pre-collection reminder cases',
    hierarchy: 9,
    isActive: true,
    permissions: {
      menus: { user: true, preCollection: true },
      subMenus: {
        user: { findOne: true },
        preCollection: { list: true, paymentRecord: true, allList: true },
      },
      dataAccess: { viewAssignedLoans: true },
      actions: { viewLoans: true },
    },
  },
  {
    name: 'customer-service',
    displayName: 'Customer Service',
    description: 'Lookup-focused support role',
    hierarchy: 10,
    isActive: true,
    permissions: {
      menus: { user: true },
      subMenus: { user: { findOne: true } },
      dataAccess: { viewAllUsers: true },
      actions: { viewUsers: true },
    },
  },
];

async function seedRoles() {
  await connectDB();
  console.log('Seeding roles...');

  for (const roleData of defaultRoles) {
    const [, created] = await Role.upsert(roleData);
    console.log(`${created ? 'Created' : 'Updated'} role: ${roleData.displayName}`);
  }

  console.log('✅ Role seeding complete.');
  process.exit(0);
}

seedRoles().catch((err) => {
  console.error('❌ Seed error:', err.message);
  process.exit(1);
});
